/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.13/userguide/multi_project_builds.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

pluginManagement {
    // TODO: Remove JitPack and resolutionStrategy after gradle-release plugin publishes
    //  a version > 3.1.0 with configuration cache support for Gradle 9.
    //  See: https://github.com/researchgate/gradle-release/pull/405
    repositories {
        maven("https://jitpack.io")
        gradlePluginPortal()
    }
    resolutionStrategy {
        eachPlugin {
            if (requested.id.id == "net.researchgate.release") {
                useModule("com.github.researchgate:gradle-release:3572e97d47")
            }
        }
    }
}

plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}

rootProject.name = "protoc-gen-java-records"

include("example")

include("protoc-gen-java-records")
